### ISSUE TITLE
NotFoundError (see above for traceback): Key resnet_v1_50/rpn_conv/3x3/weights not found in checkpoint

### ISSUE THREAD

**Issue by kelly329** [vt-vl-lab/iCAN#17]
Hi Chen,
In order to test on my own images, I follow steps in the Demo/Test on your own images section.
I encountered an issue when doing the step3(Detect all objects).

```
(sence-graph) nadoudou@nadoudou-ThinkStation-P310:~/iCAN$ python ../tf-faster-rcnn/tools/Object_Detector.py --img_dir demo/ --img_format png --Demo_RCNN demo/Object_Detection.pkl
2018-12-11 15:02:48.221898: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2018-12-11 15:02:48.221920: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2018-12-11 15:02:48.221925: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2018-12-11 15:02:48.221930: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2018-12-11 15:02:48.221934: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
2018-12-11 15:02:49.798437: W tensorflow/core/framework/op_kernel.cc:1158] Not found: Key resnet_v1_50/rpn_conv/3x3/weights not found in checkpoint
2018-12-11 15:02:49.798742: W tensorflow/core/framework/op_kernel.cc:1158] Not found: Key resnet_v1_50/rpn_conv/3x3/biases not found in checkpoint
2018-12-11 15:02:49.799248: W tensorflow/core/framework/op_kernel.cc:1158] Not found: Key resnet_v1_50/bbox_pred/biases not found in checkpoint
2018-12-11 15:02:49.799520: W tensorflow/core/framework/op_kernel.cc:1158] Not found: Key resnet_v1_50/bbox_pred/weights not found in checkpoint
2018-12-11 15:02:49.799539: W tensorflow/core/framework/op_kernel.cc:1158] Not found: Key resnet_v1_50/rpn_cls_score/weights not found in checkpoint
2018-12-11 15:02:49.800069: W tensorflow/core/framework/op_kernel.cc:1158] Not found: Key resnet_v1_50/rpn_cls_score/biases not found in checkpoint
2018-12-11 15:02:49.800601: W tensorflow/core/framework/op_kernel.cc:1158] Not found: Key resnet_v1_50/rpn_bbox_pred/weights not found in checkpoint
2018-12-11 15:02:49.801182: W tensorflow/core/framework/op_kernel.cc:1158] Not found: Key resnet_v1_50/rpn_bbox_pred/biases not found in checkpoint
2018-12-11 15:02:49.804062: W tensorflow/core/framework/op_kernel.cc:1158] Not found: Key resnet_v1_50/cls_score/weights not found in checkpoint
2018-12-11 15:02:49.804685: W tensorflow/core/framework/op_kernel.cc:1158] Not found: Key resnet_v1_50/cls_score/biases not found in checkpoint
Traceback (most recent call last):
  File "../tf-faster-rcnn/tools/Object_Detector.py", line 68, in <module>
    saver.restore(sess, tfmodel)
  File "/home/nadoudou/anaconda2/envs/sence-graph/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1548, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/home/nadoudou/anaconda2/envs/sence-graph/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 789, in run
    run_metadata_ptr)
  File "/home/nadoudou/anaconda2/envs/sence-graph/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 997, in _run
    feed_dict_string, options, run_metadata)
  File "/home/nadoudou/anaconda2/envs/sence-graph/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1132, in _do_run
    target_list, options, run_metadata)
  File "/home/nadoudou/anaconda2/envs/sence-graph/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1152, in _do_call
    raise type(e)(node_def, op, message)
NotFoundError: Key resnet_v1_50/rpn_conv/3x3/weights not found in checkpoint
	 [[Node: save/RestoreV2_274 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_save/Const_0_0, save/RestoreV2_274/tensor_names, save/RestoreV2_274/shape_and_slices)]]

Caused by op u'save/RestoreV2_274', defined at:
  File "../tf-faster-rcnn/tools/Object_Detector.py", line 67, in <module>
    saver = tf.train.Saver()
  File "/home/nadoudou/anaconda2/envs/sence-graph/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1139, in __init__
    self.build()
  File "/home/nadoudou/anaconda2/envs/sence-graph/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1170, in build
    restore_sequentially=self._restore_sequentially)
  File "/home/nadoudou/anaconda2/envs/sence-graph/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 691, in build
    restore_sequentially, reshape)
  File "/home/nadoudou/anaconda2/envs/sence-graph/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 407, in _AddRestoreOps
    tensors = self.restore_op(filename_tensor, saveable, preferred_shard)
  File "/home/nadoudou/anaconda2/envs/sence-graph/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 247, in restore_op
    [spec.tensor.dtype])[0])
  File "/home/nadoudou/anaconda2/envs/sence-graph/lib/python2.7/site-packages/tensorflow/python/ops/gen_io_ops.py", line 640, in restore_v2
    dtypes=dtypes, name=name)
  File "/home/nadoudou/anaconda2/envs/sence-graph/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/home/nadoudou/anaconda2/envs/sence-graph/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2506, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/nadoudou/anaconda2/envs/sence-graph/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1269, in __init__
    self._traceback = _extract_stack()

NotFoundError (see above for traceback): Key resnet_v1_50/rpn_conv/3x3/weights not found in checkpoint
	 [[Node: save/RestoreV2_274 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_save/Const_0_0, save/RestoreV2_274/tensor_names, save/RestoreV2_274/shape_and_slices)]]
```
many thanks!

**Comment by gaochen315** [comment]
Hi,

Sorry for my late reply. The reason you faced this issue is that you haven't downloaded the pre-trained weights for the object detector. A simple fix is to run line 72~75 in download_dataset.sh. This script will download the pre-trained weights and put them in the right place.

Let me know if this works for you.

**Comment by kelly329** [comment]
Hi Chen,

Thanks for your reply and guidance.

Now it works fine.

I think the issue can be closed.

Thanks again!
